# Generated by Django 6.0.4 on 2026-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_learningpath_pathstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='source_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
