# Generated by Django 6.0.4 on 2026-05-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_source_hash_note_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='linked_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='api.pathstep'),
        ),
    ]
