# Generated by Django 6.0.4 on 2026-05-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='actual_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
