# Generated by Django 6.0.4 on 2026-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_habit_target_value_habitlog_actual_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='weekdays',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_of_day',
            field=models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='anytime', max_length=10),
        ),
    ]
