# Generated by Django 6.0.4 on 2026-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_habit_weekdays_alter_habit_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
