# Generated by Django 6.0.4 on 2026-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_habit_streak_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
